# W206 Cluster Inventory
# actor-IaC用インベントリファイル

# 全計算ノード
[compute]
node13 actoriac_host=192.168.5.13
node14 actoriac_host=192.168.5.14
node15 actoriac_host=192.168.5.15
node21 actoriac_host=192.168.5.21
node22 actoriac_host=192.168.5.22
node23 actoriac_host=192.168.5.23

[compute:vars]
actoriac_user=devteam

# x86_64ノードのみ（ARMを除く）
[x86]
node13 actoriac_host=192.168.5.13
node14 actoriac_host=192.168.5.14
node21 actoriac_host=192.168.5.21
node22 actoriac_host=192.168.5.22
node23 actoriac_host=192.168.5.23

[x86:vars]
actoriac_user=devteam

# NVIDIA GPU搭載ノード
[nvidia]
node13 actoriac_host=192.168.5.13
node14 actoriac_host=192.168.5.14
node15 actoriac_host=192.168.5.15
node21 actoriac_host=192.168.5.21
node22 actoriac_host=192.168.5.22

[nvidia:vars]
actoriac_user=devteam

# AMD GPU搭載ノード
[amd]
node23 actoriac_host=192.168.5.23

[amd:vars]
actoriac_user=devteam

# MicroK8sクラスタ
[microk8s]
node21 actoriac_host=192.168.5.21
node22 actoriac_host=192.168.5.22
node23 actoriac_host=192.168.5.23

[microk8s:vars]
actoriac_user=devteam
